/* * PROJECT: Stargate Node v2 - Master Schema Consolidation
 * USER: FINANCE_ADMIN
 * ACTION: Materializing missing tables for 7,172.23 Target
 */

-- 1. Create the Recalibration Log (Fixes ORA-00942 for SG26_RECALIBRATION_LOG)
CREATE TABLE SG26_RECALIBRATION_LOG (
    LOG_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENT_INDEX  VARCHAR2(20) DEFAULT 'SP500',
    STATUS         VARCHAR2(50),
    TARGET_PX      NUMBER(10,2),
    LAST_UPDATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create the Momentum Table (Fixes ORA-00942 for SG26_SECTOR_MOMENTUM)
CREATE TABLE SG26_SECTOR_MOMENTUM (
    SECTOR_NAME   VARCHAR2(100),
    WEIGHT_DELTA  NUMBER(5,2),
    SYNC_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Seed the 7,172.23 Technical Baseline
INSERT INTO SG26_RECALIBRATION_LOG (STATUS, TARGET_PX) VALUES ('TARGET_RECLAIMED', 7172.23);
INSERT INTO SG26_SECTOR_MOMENTUM (SECTOR_NAME, WEIGHT_DELTA) VALUES ('Information Tech', 34.2);
INSERT INTO SG26_SECTOR_MOMENTUM (SECTOR_NAME, WEIGHT_DELTA) VALUES ('Energy', 2.87);

-- 4. Create the Portfolio mapping (Internal Reference)
CREATE TABLE PORTFOLIO_POSITIONS (
    TICKER VARCHAR2(10),
    ALLOCATION_PCT NUMBER(5,2)
);
INSERT INTO PORTFOLIO_POSITIONS VALUES ('DRAM', 25.00);
INSERT INTO PORTFOLIO_POSITIONS VALUES ('XLE', 5.00);

-- 5. Build the Master Executive View
CREATE OR REPLACE VIEW VW_STARGATE_EXECUTIVE_SUMMARY AS
SELECT 
    l.TARGET_PX AS "Sovereign Target",
    l.STATUS AS "Mission Status",
    (SELECT WEIGHT_DELTA || '% (CONCENTRATED)' FROM SG26_SECTOR_MOMENTUM WHERE SECTOR_NAME = 'Information Tech') AS "Tech Momentum",
    (SELECT WEIGHT_DELTA || '% (COMPRESSED)' FROM SG26_SECTOR_MOMENTUM WHERE SECTOR_NAME = 'Energy') AS "Energy Risk",
    (SELECT ALLOCATION_PCT || '% (DRAM)' FROM PORTFOLIO_POSITIONS WHERE TICKER = 'DRAM') AS "Hardware Beta",
    l.LAST_UPDATE
FROM SG26_RECALIBRATION_LOG l
WHERE l.LOG_ID = (SELECT MAX(LOG_ID) FROM SG26_RECALIBRATION_LOG);

COMMIT;

-- 6. Verification
SET LINESIZE 200;
SELECT * FROM VW_STARGATE_EXECUTIVE_SUMMARY;
