/* * PROJECT: Stargate Node v2 - Final Infrastructure Fix
 * ACTION: Re-aligning SG26 for 7,172.23 Reclamation
 * NODE: Rio de Janeiro / São Paulo Sync Ready
 */

-- 1. Drop the table to resolve ORA-00955 and allow schema re-alignment
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SG26_RECALIBRATION_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 2. Create the Table with the missing LOG_ID (Fixes ORA-00904)
CREATE TABLE SG26_RECALIBRATION_LOG (
    LOG_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENT_INDEX  VARCHAR2(20) DEFAULT 'SP500',
    STATUS         VARCHAR2(50),
    TARGET_PX      NUMBER(10,2),
    LAST_UPDATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Seed the current 7,172.23 Pivot
INSERT INTO SG26_RECALIBRATION_LOG (STATUS, TARGET_PX) 
VALUES ('REVERSAL_CONFIRMED', 7172.23);

-- 4. Re-establish the Strategic View
CREATE OR REPLACE VIEW VW_STARGATE_STRATEGIC_ANALYSIS AS
SELECT 
    l.CURRENT_INDEX,
    l.STATUS,
    l.TARGET_PX AS RECLAMATION_TARGET,
    (SELECT 'DRAM: ' || ALLOCATION_PCT || '% (Vertical Load)' 
     FROM PORTFOLIO_POSITIONS WHERE TICKER = 'DRAM') AS DRAM_STATUS,
    (SELECT 'XLE: ' || ALLOCATION_PCT || '% (Structural Exit)' 
     FROM PORTFOLIO_POSITIONS WHERE TICKER = 'XLE') AS XLE_STATUS,
    l.LAST_UPDATE
FROM SG26_RECALIBRATION_LOG l
WHERE l.LOG_ID = (SELECT MAX(LOG_ID) FROM SG26_RECALIBRATION_LOG);

COMMIT;

-- 5. Show Final Verified Results
SET LINESIZE 200;
SELECT * FROM VW_STARGATE_STRATEGIC_ANALYSIS;
