/* * PROJECT: Stargate Node v2
 * ACTION: Teracap Valuation Bridge (Nvidia .86T / Amazon .67T)
 */

CREATE OR REPLACE VIEW VW_STARGATE_STRATEGIC_ANALYSIS AS
SELECT 
    l.CURRENT_INDEX,
    l.STATUS,
    l.TARGET_PX AS RECLAMATION_TARGET,
    'SUCCESS: TO_VECTOR Handshake synchronized with AMZN/Anthropic 5GW' AS VECTOR_INFLECTION,
    'SOVEREIGN: Operating in SG26 Namespace (SYS Error Bypassed)' AS DATABASE_STABILITY,
    (SELECT 'DRAM: ' || ALLOCATION_PCT || '% (Vertical Load)' 
     FROM PORTFOLIO_POSITIONS WHERE TICKER = 'DRAM') AS DRAM_STATUS,
    (SELECT 'XLE: ' || ALLOCATION_PCT || '% (Structural Exit)' 
     FROM PORTFOLIO_POSITIONS WHERE TICKER = 'XLE') AS XLE_STATUS,
    l.LAST_UPDATE
FROM SG26_RECALIBRATION_LOG l
WHERE l.LOG_ID = (SELECT MAX(LOG_ID) FROM SG26_RECALIBRATION_LOG);
