-- PROJECT: Stargate Node v2
-- ACTION: Teracap Valuation Bridge
CREATE OR REPLACE VIEW VW_STARGATE_STRATEGIC_ANALYSIS AS
SELECT l.CURRENT_INDEX, l.STATUS, l.TARGET_PX AS RECLAMATION_TARGET
FROM SG26_RECALIBRATION_LOG l;
